export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const USER_LOGOUT = "USER_LOGOUT";

export const TOPIC_FETCH = "TOPIC_FETCH";
export const TOPIC_FETCH_SUCCESS = "TOPIC_FETCH_SUCCESS";
